language: python
os: linux
dist: bionic
python: 3.7
branches:
  only:
  - master
cache:
  pip: true
install: pip install -r requirements.txt
script:
- python update.py
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- sh ci-push.sh
notifications:
  slack:
    secure: Ptc5MmZ+jUWCkK2Ej1AY1sbhikdtuq1WrLvuV5+PnVgRqCSzImx4q8Wd3gSVc5A4iR9vZS0+tyLay1vcFo2RUVYSuwwftqba1OHIkrlf9833C8ysCcrZxya5Eolrmaurw5sfE6LDgISprQhEbhWBvldyxkNbvwxShGNoer4lSkbHlvZEc2yPrmjkeLg9+v9R69oEQy0155jTGrFbcnVxQXsip4xofpMw1MtdicVZHJghn0MmCbmNw5KDgp2yU2tM0g20P7JihCG6haKlDvWVNWMiOzbGG9lzoZRZ8KFL9VzZLeVUvs7ma81Z2HmqQ9Pjom7oY/hAuddAJmcYWcRoVvMbNR9PDaSyl3Vmpl+hHXAnS6UvtVwF0woE9hzm1aSt2JJqmMlBl2HPmBxVTfU7gzZSdNKDLIQiX5Wn9VizspFyiTse4+ArPIC2XYeX1PkzWCsIhkGRzF+BJXkq3A1oASTU3JSxs6fwK35wYmjCxObk7gOTjXhFZlaEO9zYrvxR2wx+rkMJxjrVYfrCdeaHIBD1hZ4h3QrMrjlBhPO737insUIYxiJDXmloDbo2jWT1iav5HvuFoAxaI1prTxFPo1zKCtQqUM9KUkBGM/CBOuilpy4+KweIj5vLcE6Yb3LmpKAEq2bQj/iZARG7O8cDJ/9lC/1/d3OeLnYGslMsjH0=
